FROM node:24-alpine AS builder
RUN npm i -g pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
ENV DATABASE_URL postgresql://badertech:secret@db/badertechdb
ENV NEXT_PUBLIC_SERVER_URL https://badertech.codenik.in
ENV NEXT_PUBLIC_ORG_NAME Badertech
ENV NODE_ENV production
ENV PAYLOAD_SECRET secret
COPY . .
RUN pnpm build
FROM node:24-alpine AS prod
WORKDIR /app
COPY --from=builder /app/.next/standalone/ .
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static .next/static
ENV NODE_ENV production
EXPOSE 3000
CMD HOSTNAME="0.0.0.0" node server.js
